package com.mcmlr.system.products.minetunes

import com.mcmlr.blocks.api.app.StringResource

enum class S {
    MINE_TUNES_TITLE,
    HOME_BUTTON,
    MUSIC_BUTTON,
    SEARCH_BUTTON,
    SEARCH_TITLE,
    SEARCH_PLACEHOLDER,
    SEARCH_SONGS_BUTTON,
    SEARCH_ARTISTS_BUTTON,
    SEARCH_PLAYLISTS_BUTTON,
    SEARCH_ALBUMS_BUTTON,

    PLAYER_TITLE,
    PLAY_BUTTON,
    PAUSE_BUTTON,
    ADD_BUTTON,
    OPTIONS_BUTTON,
    NEXT_TRACK_BUTTON,
    LAST_TRACK_BUTTON,
    LOOP_BUTTON,
    SHUFFLE_BUTTON,
    UP_ARROW_BUTTON,
    DOWN_ARROW_BUTTON,

    LIBRARY_TITLE,
    LIBRARY_SEARCH_PLACEHOLDER,
    LIBRARY_CREATE_PLAYLIST_BUTTON,

    ARTIST_TITLE,
    ARTIST_STATS_PLACEHOLDER,
    ARTIST_PLAYS_PLACEHOLDER,
    ARTIST_SEE_ALL_SONGS_BUTTON,
    ARTIST_POPULAR_SONGS_TITLE,
    ARTIST_ALL_SONGS_TITLE,
    ARTIST_ALBUMS_TITLE,

    CREATE_PLAYLIST_TITLE,
    CREATE_PLAYLIST_NAME_PLACEHOLDER,
    CREATE_PLAYLIST_SELECT_ICON,
    CREATE_PLAYLIST_CREATE_BUTTON,
    CREATE_PLAYLIST_UPDATE_BUTTON,
    CREATE_PLAYLIST_CANCEL_BUTTON,

    PLAYLIST_TITLE,

    PLAYLIST_PICKER_TITLE,
    ;

    fun resource(): StringResource = StringResource("mine tunes", this.name)
}
