package com.mcmlr.system.products.announcements

import com.mcmlr.blocks.api.app.StringResource

enum class S {
    ANNOUNCEMENTS,
    ANNOUNCEMENTS_MESSAGE,
    CREATE_NEW_POST,
    EDIT_POSTS,
    ANNOUNCEMENT_CREATED_MESSAGE,
    ANNOUNCEMENT_UPDATED_MESSAGE,
    ANNOUNCEMENT_DELETED_MESSAGE,
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST,
    POST_TITLE,
    POST_TITLE_MESSAGE,
    SET_POSTS_TITLE,
    POST_MESSAGE,
    POST_MESSAGE_MESSAGE,
    SET_POSTS_MESSAGE,
    ADD_A_CTA,
    ENABLE_CTA_MESSAGE,
    ON,
    OFF,
    CTA_TEXT,
    CTA_TEXT_MESSAGE,
    SET_POST_CTA_TEXT,
    CTA_ACTION_TITLE,
    CTA_ACTION_MESSAGE,
    CTA_ACTION_TEXT,
    CTA_ACTION_TYPE_TITLE,
    CTA_ACTION_TYPE_MESSAGE,
    MISSING_TITLE_ERROR_MESSAGE,
    MISSING_MESSAGE_ERROR_MESSAGE,
    MISSING_CTA_TEXT_ERROR_MESSAGE,
    MISSING_CTA_ACTION_ERROR_MESSAGE,
    ANNOUNCEMENT_SELECTOR_TITLE,
    ;

    fun resource(): StringResource = StringResource("announcements", this.name)
}