package com.mcmlr.system.products.homes

import com.mcmlr.blocks.api.app.StringResource

enum class S {
    HOMES,
    ADD_NEW_HOME,
    REMOVE_HOME,
    CANCEL,
    EMPTY_HOMES_MESSAGE,
    MAX_HOMES_ERROR,
    TELEPORT_WAIT_MESSAGE,
    TELEPORT_DELAY_MESSAGE,
    ADD_HOME_TITLE,
    ADD_HOME_INPUT,
    SELECT_ICON,
    SAVE_HOME,
    UNKNOWN_ERROR_MESSAGE,
    HOMES_CONFIG_TITLE,
    MAX_HOMES_TITLE,
    MAX_HOMES_MESSAGE,
    DEFAULT_MAX_HOMES,
    CONFIG_TELEPORT_DELAY_TITLE,
    CONFIG_TELEPORT_DELAY_MESSAGE,
    CONFIG_TELEPORT_DEFAULT,
    CONFIG_TELEPORT_COOLDOWN_TITLE,
    CONFIG_TELEPORT_COOLDOWN_MESSAGE,
    MAX_HOMES_TEXT,
    SECONDS_TEXT,
    MAX_HOMES_WHOLE_NUMBERS_ERROR,
    DELAY_WHOLE_NUMBERS_ERROR,
    COOLDOWN_WHOLE_NUMBERS_ERROR,
    PLURAL,
    ;

    fun resource(): StringResource = StringResource("homes", this.name)
}