package com.mcmlr.system.products.teleport

import com.mcmlr.blocks.api.app.StringResource

enum class S {
    TELEPORT_TITLE,
    PLAYERS_TAB,
    REQUESTS_TAB,
    PLAYERS_BUTTON,
    REQUESTS_BUTTON,
    EMPTY_REQUESTS_TEXT,
    EMPTY_PLAYERS_TEXT,
    SEND_REQUEST_TITLE,
    PLAYER_NAME,
    TELEPORT_TO_PLAYER_BUTTON,
    TELEPORT_TO_YOU_BUTTON,
    SENT_REQUEST_MESSAGE,
    UPDATE_REQUEST_MESSAGE,
    ERROR_REQUEST_MESSAGE,
    REQUEST_PLAYER_TELEPORT_CHAT_MESSAGE,
    REQUEST_TELEPORT_HOVER_MESSAGE,
    REQUEST_CHAT_CTA,
    REQUEST_YOU_TELEPORT_CHAT_MESSAGE,
    TELEPORT_RESPOND_TITLE,
    ACCEPT,
    REJECT,
    COOLDOWN_ERROR_MESSAGE,
    PASSENGER_MESSAGE,
    DESTINATION_MESSAGE,
    PLURAL,
    TELEPORT_CONFIG_FILE,
    CONFIG_DELAY_TITLE,
    CONFIG_DELAY_MESSAGE,
    CONFIG_DEFAULT_WAIT_VALUE,
    CONFIG_COOLDOWN_TITLE,
    CONFIG_COOLDOWN_MESSAGE,
    CONFIG_INPUT_SECONDS_PLACEHOLDER,
    CONFIG_DELAY_ERROR_MESSAGE,
    CONFIG_COOLDOWN_ERROR_MESSAGE,
    ;

    fun resource(): StringResource = StringResource("teleport", this.name)
}